-- MySQL Script generated by MySQL Workbench
-- dom 16 mai 2021 22:03:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NiceEvaluation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NiceEvaluation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NiceEvaluation` ;
USE `NiceEvaluation` ;

-- -----------------------------------------------------
-- Table `NiceEvaluation`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NiceEvaluation`.`Usuario` (
  `nomeUsuario` VARCHAR(25) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `hashAndSalt` CHAR(64) NOT NULL,
  `salt` CHAR(8) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nomeUsuario`, `email`),
  UNIQUE INDEX `nomeUsuario_UNIQUE` (`nomeUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NiceEvaluation`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NiceEvaluation`.`Materia` (
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(160) NULL,
  PRIMARY KEY (`nome`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NiceEvaluation`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NiceEvaluation`.`Administrador` (
  `Usuario_nomeUsuario` VARCHAR(25) NOT NULL,
  `Usuario_email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Usuario_nomeUsuario`, `Usuario_email`),
  CONSTRAINT `fk_Administrador_Usuario`
    FOREIGN KEY (`Usuario_nomeUsuario` , `Usuario_email`)
    REFERENCES `NiceEvaluation`.`Usuario` (`nomeUsuario` , `email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NiceEvaluation`.`Questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NiceEvaluation`.`Questao` (
  `idQuestao` INT(9) NOT NULL AUTO_INCREMENT,
  `itens` JSON NULL,
  `corpo` TEXT NOT NULL,
  `resposta` TEXT NOT NULL,
  `Administrador_Usuario_nomeUsuario` VARCHAR(25) NULL,
  `Administrador_Usuario_email` VARCHAR(50) NULL,
  `Materia_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idQuestao`, `Administrador_Usuario_nomeUsuario`, `Administrador_Usuario_email`, `Materia_nome`),
  INDEX `fk_Questao_Administrador1_idx` (`Administrador_Usuario_nomeUsuario` ASC, `Administrador_Usuario_email` ASC) VISIBLE,
  INDEX `fk_Questao_Materia1_idx` (`Materia_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Questao_Administrador1`
    FOREIGN KEY (`Administrador_Usuario_nomeUsuario` , `Administrador_Usuario_email`)
    REFERENCES `NiceEvaluation`.`Administrador` (`Usuario_nomeUsuario` , `Usuario_email`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Questao_Materia1`
    FOREIGN KEY (`Materia_nome`)
    REFERENCES `NiceEvaluation`.`Materia` (`nome`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NiceEvaluation`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NiceEvaluation`.`Professor` (
  `Usuario_nomeUsuario` VARCHAR(25) NOT NULL,
  `Usuario_email` VARCHAR(50) NOT NULL,
  `Administrador_Usuario_nomeUsuario` VARCHAR(25) NULL,
  `Administrador_Usuario_email` VARCHAR(50) NULL,
  PRIMARY KEY (`Usuario_nomeUsuario`, `Usuario_email`, `Administrador_Usuario_nomeUsuario`, `Administrador_Usuario_email`),
  INDEX `fk_Professor_Administrador1_idx` (`Administrador_Usuario_nomeUsuario` ASC, `Administrador_Usuario_email` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Usuario1`
    FOREIGN KEY (`Usuario_nomeUsuario` , `Usuario_email`)
    REFERENCES `NiceEvaluation`.`Usuario` (`nomeUsuario` , `email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Professor_Administrador1`
    FOREIGN KEY (`Administrador_Usuario_nomeUsuario` , `Administrador_Usuario_email`)
    REFERENCES `NiceEvaluation`.`Administrador` (`Usuario_nomeUsuario` , `Usuario_email`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NiceEvaluation`.`Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NiceEvaluation`.`Tema` (
  `nome` VARCHAR(30) NOT NULL,
  `Materia_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`, `Materia_nome`),
  INDEX `fk_Tema_Materia1_idx` (`Materia_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Tema_Materia1`
    FOREIGN KEY (`Materia_nome`)
    REFERENCES `NiceEvaluation`.`Materia` (`nome`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NiceEvaluation`.`Questao_has_Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NiceEvaluation`.`Questao_has_Tema` (
  `Questao_idQuestao` INT(9) NOT NULL,
  `Questao_Administrador_Usuario_nomeUsuario` VARCHAR(25) NOT NULL,
  `Questao_Administrador_Usuario_email` VARCHAR(50) NOT NULL,
  `Questao_Materia_nome` VARCHAR(45) NOT NULL,
  `Tema_nome` VARCHAR(30) NOT NULL,
  `Tema_Materia_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Questao_idQuestao`, `Questao_Administrador_Usuario_nomeUsuario`, `Questao_Administrador_Usuario_email`, `Questao_Materia_nome`, `Tema_nome`, `Tema_Materia_nome`),
  INDEX `fk_Questao_has_Tema_Tema1_idx` (`Tema_nome` ASC, `Tema_Materia_nome` ASC) VISIBLE,
  INDEX `fk_Questao_has_Tema_Questao1_idx` (`Questao_idQuestao` ASC, `Questao_Administrador_Usuario_nomeUsuario` ASC, `Questao_Administrador_Usuario_email` ASC, `Questao_Materia_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Questao_has_Tema_Questao1`
    FOREIGN KEY (`Questao_idQuestao` , `Questao_Administrador_Usuario_nomeUsuario` , `Questao_Administrador_Usuario_email` , `Questao_Materia_nome`)
    REFERENCES `NiceEvaluation`.`Questao` (`idQuestao` , `Administrador_Usuario_nomeUsuario` , `Administrador_Usuario_email` , `Materia_nome`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Questao_has_Tema_Tema1`
    FOREIGN KEY (`Tema_nome` , `Tema_Materia_nome`)
    REFERENCES `NiceEvaluation`.`Tema` (`nome` , `Materia_nome`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

### Subjects definition ###
INSERT `NiceEvaluation`.`Materia` (nome, descricao) 
	VALUES(
		`Programação Web(Javascript Frameworks)`, 
		`Introdução aos conceitos básicos de Programação Web, juntamente com Javascript, HTML e CSS`
    ),
    (
		`Lógica de Programação`,
        `Conceitos básicos e iniciação à programação, lógica e algoritmos`
    ),
    (
		`PHP avançado(Laravel Framework)`,
        `Especialização do PHP e introdução ao framework Laravel`
    ),
    (
		`Python avançado(Django Framework)`,
        `Especialização em Python e introdução ao Django Framework para Python na Web`
    ),
    (
		`Linguagens de Marcação(HTML/CSS)`,
        `Conceitos básicos das linguagens de marcação mais usadas no mercado(HTML/CSS)`
    ),
    (
		`Introdução ao Java`,
        `Introdução e conceitos básicos da linguagem Java`
    ),
    (
		`Estrutura de Dados`,
        `Conceitos de estrutura e manipulação de dados e memória em programas gerais`
    ),
    (
		`Projeto de Software`,
        `Aplicação da teoria no mundo real, construção de um projeto de software do zero utilizando tudo aprendido dentroo do curso`
    ),
    (
		`Implementação em PHP`,
        `Pequena implementação de software em PHP`
    );

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
